export const ROUTES = {
  HOME: "/",
  INTERSTATE_MOVING: "/interstate-moving",
  MOVING_SERVICES: "/moving-services",
  WORLDWIDE_MOVING: "/worldwide-moving",
  FREE_MOVING_QUOTE: "/free-moving-quote",
  MOVING_TIPS: "/moving-tips",
  PODCAST: "/podcast",
  CONTACT: "/contact",
  ABOUT: "/about",
  INTERNATIONAL_CAR_SHIPPING: "/international-car-shipping",
  INTERNATIONAL_HOUSEHOLD_MOVERS: "/international-household-movers",
  MOTORCYCLE_TO_EUROPE: "/shipping-motorcycle-europe",
  MOVING_INSURANCE: "/international-moving-insurance",
  OVERSEAS_ARTWORK_SHIPPING: "/overseas-artwork-shipping",
  INTERNATIONAL_PIANO_MOVERS: "/international-piano-movers",
  PACKING_SERVICE: "/packing-service",
  COMPARING_QUOTES: "/comparing-international-moving-quotes",
  COMPANY_EMBASSY: "/company-embassy",
  CHECKOUT: "/checkout",
  THANKYOU: "/thankyou",
  WHY_TRUST_VIP: "/why-trust-vip",
  TERMS_OF_SERVICE: "/terms-of-service",
  PRIVACY_POLICY: "/privacy-policy",
  ACCESSIBILITY: "/accessibility",
};
