const PDFDocument = require('pdfkit');

/**
 * יצירת PDF לחשבונית — Phase 2.
 * מחזיר Buffer מוכן להורדה / שמירה.
 */
function generateInvoicePdf(invoice) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      const brand = process.env.COMPANY_NAME || 'VIP International Shipping';
      const currency = invoice.amounts.currency || 'USD';

      doc.fontSize(20).text(brand, { align: 'left' });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor('#555').text(process.env.COMPANY_ADDRESS || 'United States');
      doc.fillColor('#000');
      doc.moveDown();

      doc.fontSize(16).text('INVOICE', { align: 'right' });
      doc.fontSize(11).text(`Number: ${invoice.invoiceNumber}`, { align: 'right' });
      doc.text(`Status: ${String(invoice.status || '').toUpperCase()}`, { align: 'right' });
      doc.text(`Issue date: ${formatDate(invoice.issueDate)}`, { align: 'right' });
      doc.text(`Due date: ${formatDate(invoice.dueDate)}`, { align: 'right' });
      doc.moveDown();

      doc.fontSize(12).text('Bill to');
      doc.fontSize(10).fillColor('#333');
      doc.text(invoice.customer?.name || '');
      if (invoice.customer?.company) doc.text(invoice.customer.company);
      doc.text(invoice.customer?.email || '');
      if (invoice.tax?.billingAddress) {
        const a = invoice.tax.billingAddress;
        doc.text([a.line1, a.city, a.state, a.postalCode, a.country].filter(Boolean).join(', '));
      }
      doc.fillColor('#000');
      doc.moveDown();

      // Table header
      const tableTop = doc.y;
      doc.fontSize(10).text('Description', 50, tableTop, { width: 260 });
      doc.text('Qty', 320, tableTop, { width: 40 });
      doc.text('Unit', 370, tableTop, { width: 70 });
      doc.text('Total', 450, tableTop, { width: 90, align: 'right' });
      doc.moveTo(50, tableTop + 15).lineTo(545, tableTop + 15).stroke('#ccc');

      let y = tableTop + 25;
      (invoice.lineItems || []).forEach((item) => {
        doc.text(String(item.description || '').slice(0, 80), 50, y, { width: 260 });
        doc.text(String(item.quantity ?? 1), 320, y, { width: 40 });
        doc.text(money(item.unitPrice, currency), 370, y, { width: 70 });
        doc.text(money(item.total, currency), 450, y, { width: 90, align: 'right' });
        y += 22;
      });

      doc.y = y + 10;
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#ccc');
      doc.moveDown();

      const totalsX = 350;
      doc.fontSize(11);
      doc.text('Subtotal:', totalsX, doc.y, { width: 100 });
      doc.text(money(invoice.amounts.subtotal, currency), 450, doc.y, { width: 90, align: 'right' });
      doc.moveDown(0.5);

      const taxLabel = invoice.tax?.jurisdiction
        ? `Tax (${invoice.tax.jurisdiction}${invoice.tax.rate != null ? ` @ ${(invoice.tax.rate * 100).toFixed(2)}%` : ''}):`
        : 'Tax:';
      doc.text(taxLabel, totalsX, doc.y, { width: 100 });
      doc.text(money(invoice.amounts.taxAmount || 0, currency), 450, doc.y, { width: 90, align: 'right' });
      doc.moveDown(0.5);

      doc.fontSize(13).text('Total:', totalsX, doc.y, { width: 100 });
      doc.text(money(invoice.amounts.totalAmount, currency), 450, doc.y, { width: 90, align: 'right' });
      doc.moveDown(2);

      if (invoice.payment?.paidAt) {
        doc.fontSize(10).fillColor('#0a7').text(
          `Paid ${money(invoice.payment.paidAmount, currency)} on ${formatDate(invoice.payment.paidAt)}` +
          (invoice.payment.reference ? ` (ref: ${invoice.payment.reference})` : '')
        );
        doc.fillColor('#000');
      }

      if (invoice.notes) {
        doc.moveDown();
        doc.fontSize(10).fillColor('#555').text(`Notes: ${invoice.notes}`);
        doc.fillColor('#000');
      }

      doc.moveDown(2);
      doc.fontSize(8).fillColor('#888').text(
        'This invoice is generated by VIP International Shipping. US sales tax is calculated based on destination state and company nexus, or via Stripe Tax when enabled.',
        { align: 'left', width: 495 }
      );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

function money(value, currency) {
  const n = Number(value) || 0;
  return `${currency} ${n.toFixed(2)}`;
}

function formatDate(d) {
  if (!d) return '-';
  const date = new Date(d);
  if (Number.isNaN(date.getTime())) return '-';
  return date.toISOString().slice(0, 10);
}

module.exports = { generateInvoicePdf };
